ALTER TABLE TR_REG_ASSET DROP PRIMARY KEY;
ALTER TABLE `TR_REG_ASSET` ADD `ID` INT(11) NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`ID`);
ALTER TABLE TR_REG_ASSET_DETAIL_PO DROP PRIMARY KEY;
ALTER TABLE `TR_REG_ASSET_DETAIL_PO`
ADD `ID` INT
(11) NOT NULL AUTO_INCREMENT FIRST,
ADD `ASSET_REG_ID` INT
(11) NOT NULL AFTER `ID`,
ADD PRIMARY KEY
(`ID`);
ALTER TABLE `TR_REG_ASSET_DETAIL_PO`
ADD INDEX
(`ASSET_REG_ID`);
ALTER TABLE `TR_REG_ASSET_DETAIL_PO`
ADD CONSTRAINT `FK_ASSET_REG_ID` FOREIGN KEY
(`ASSET_REG_ID`) REFERENCES `fams`.`TR_REG_ASSET`
(`ID`) ON
DELETE RESTRICT ON
UPDATE RESTRICT;
ALTER TABLE TR_REG_ASSET_DETAIL DROP PRIMARY KEY;
ALTER TABLE `TR_REG_ASSET_DETAIL`
ADD `ID` INT
(11) NOT NULL AUTO_INCREMENT FIRST,
ADD `ASSET_PO_ID` INT
(11) NOT NULL AFTER `ID`,
ADD PRIMARY KEY
(`ID`);
ALTER TABLE `TR_REG_ASSET_DETAIL`
ADD INDEX
(`NO_REG_ITEM`);
TABLE `TR_REG_ASSET_DETAIL`
ADD INDEX
(`ASSET_PO_ID`);
ALTER TABLE `TR_REG_ASSET_DETAIL`
ADD CONSTRAINT `FK_ASSET_PO_ID` FOREIGN KEY
(`ASSET_PO_ID`) REFERENCES `fams`.`TR_REG_ASSET_DETAIL_PO`
(`ID`) ON
DELETE RESTRICT ON
UPDATE RESTRICT;
ALTER TABLE TR_REG_ASSET_DETAIL_FILE DROP PRIMARY KEY;
ALTER TABLE `TR_REG_ASSET_DETAIL_FILE`
ADD `ID` INT
(11) NOT NULL AUTO_INCREMENT FIRST,
ADD `ASSET_PO_ID` INT
(11) NOT NULL AFTER `ID`,
ADD PRIMARY KEY
(`ID`);
ALTER TABLE `TR_REG_ASSET_DETAIL_FILE`
ADD INDEX
(`ASSET_PO_ID`);
ALTER TABLE `TR_REG_ASSET_DETAIL_FILE`
ADD CONSTRAINT `FK_FILE_ALTER_ASSET_PO_ID ` FOREIGN KEY
(`ASSET_PO_ID`) REFERENCES `fams`.`TR_REG_ASSET_DETAIL_PO`
(`ID`) ON
DELETE RESTRICT ON
UPDATE RESTRICT;
ALTER TABLE TR_REG_ASSET_FILE DROP PRIMARY KEY;
ALTER TABLE `TR_REG_ASSET_FILE`
ADD `ID` INT
(11) NOT NULL AUTO_INCREMENT FIRST,
ADD `ASSET_REG_ID` INT
(11) NOT NULL AFTER `ID`,
ADD PRIMARY KEY
(`ID`);
ALTER TABLE `TR_REG_ASSET_FILE`
ADD INDEX
(`ASSET_REG_ID`);
ALTER TABLE `TR_REG_ASSET_FILE`
ADD CONSTRAINT `FK_FILE_ASSET_PO_ID` FOREIGN KEY
(`ASSET_REG_ID`) REFERENCES `fams`.`TR_REG_ASSET`
(`ID`) ON
DELETE RESTRICT ON
UPDATE RESTRICT;
ALTER TABLE `TR_REG_ASSET_DETAIL` CHANGE `ASSET_PO_ID` `ASSET_DETAIL_PO_ID` INT
(11) NOT NULL;
ALTER TABLE `TR_REG_ASSET_DETAIL`
DROP FOREIGN KEY `FK_ASSET_PO_ID`;
ALTER TABLE `TR_REG_ASSET_DETAIL`
ADD CONSTRAINT `FK_ASSET_DETAIL_PO_ID` FOREIGN KEY
(`ASSET_DETAIL_PO_ID`) REFERENCES `fams`.`TR_REG_ASSET_DETAIL`
(`ID`) ON
DELETE RESTRICT ON
UPDATE RESTRICT;
ALTER TABLE `TR_REG_ASSET_DETAIL` CHANGE `ASSET_DETAIL_PO_ID` `ASSET_PO_ID` INT
(11) NOT NULL;
ALTER TABLE `TR_REG_ASSET_DETAIL`
DROP FOREIGN KEY `FK_ASSET_DETAIL_PO_ID`;
ALTER TABLE `TR_REG_ASSET_DETAIL`
ADD CONSTRAINT `FK_ASSET_PO_ID` FOREIGN KEY
(`ASSET_PO_ID`) REFERENCES `fams`.`TR_REG_ASSET`
(`ID`) ON
DELETE RESTRICT ON
UPDATE RESTRICT;
ALTER TABLE `TR_REG_ASSET_DETAIL_FILE` CHANGE `ASSET_PO_ID` `ASSET_PO_IDETAIL_D` INT
(11) NOT NULL;
ALTER TABLE `TR_REG_ASSET_DETAIL_FILE`
DROP FOREIGN KEY `FK_FILE_ALTER_ASSET_PO_ID `;
ALTER TABLE `TR_REG_ASSET_DETAIL_FILE`
ADD CONSTRAINT `FK_FILE_ALTER_ASSET_PO_ID ` FOREIGN KEY
(`ASSET_PO_IDETAIL_D`) REFERENCES `fams`.`TR_REG_ASSET_DETAIL`
(`ID`) ON
DELETE RESTRICT ON
UPDATE RESTRICT;
ALTER TABLE `TR_REG_ASSET_DETAIL`
DROP FOREIGN KEY `FK_ASSET_PO_ID`;
ALTER TABLE `TR_REG_ASSET_DETAIL`
ADD CONSTRAINT `FK_ASSET_PO_ID` FOREIGN KEY
(`ASSET_PO_ID`) REFERENCES `fams`.`TR_REG_ASSET_DETAIL_PO`
(`ID`) ON
DELETE RESTRICT ON
UPDATE RESTRICT;
ALTER TABLE `TR_REG_ASSET_DETAIL_FILE` CHANGE `ASSET_PO_IDETAIL_D` `ASSET_PO_IDETAIL_ID` INT
(11) NOT NULL;
ALTER TABLE `TR_REG_ASSET_DETAIL_FILE` CHANGE `ASSET_PO_IDETAIL_ID` `ASSET_PO_DETAIL_ID` INT
(11) NOT NULL;


ALTER TABLE `TR_REG_ASSET_DETAIL_FILE`
ADD INDEX
(`ASSET_PO_DETAIL_ID`);
ALTER TABLE `TR_REG_ASSET_DETAIL_FILE`
ADD UNIQUE
(`ID`);